### ISSUE TITLE
Does it support esp32?

### ISSUE THREAD

**Issue by arahasya** [Seeed-Studio/Seeed_Arduino_UltrathinLEDMatrix#7]
Which models of Arduino does this library support?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

May I ask if you have solved this problem so far?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
